# Docker compose file with a mongodb container
version: '3.8'
services:
  db:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: payloady
      MONGO_INITDB_DATABASE: payloady
    command:
      - --auth
volumes:
  db-data: